source "https://rubygems.org"

ruby "2.6.2"

gem "bourbon"
gem "builder"
gem "middleman"
gem "middleman-blog"
gem "middleman-inline_svg"
gem "middleman-autoprefixer"
gem "middleman-minify-html"
gem "middleman-livereload"
# gem "neat"
gem "redcarpet"
gem "sassc"
